# Generated by Django 5.0.6 on 2024-06-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order_totalprice_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
